exports = [
    "Mega Forte",
    "Irmãos Kedi",
    "Martins",
    "Peixoto",
    "ARCOM",
    "Aliança",
    "Makro",
    "JC Distribuição",
    "Profarma",
    "Tambasa",
    "Rio Vermelho",
    "Assaí Atacadista",
    "Roldão Atacadista",
    "Extra",
    "Carrefour Granja Julieta",
    "Pão de Açúcar",
    "Ceagesp",
    "Vila Nova",
    "Zamboni",
    "Cantu Alimentos",
    "Rio do Peixe",
    "Ferragens Negrão",
    "Teruya Ferramentas",
    "Adauto de Carvalho",
    "Mundial Center",
    "Embrasil",
    "A G Mercadinho",
    "B C A Com. S.A.",
    "Condor",
    "Eletoleste",
    "Almeida Com. Dist Mat Constr",
    "Objetiva",
    "Ferragens Ramada",
    "Casa do Lojista",
    "M J R Cunha",
    "Cardão Com Imp Ltda",
    "Diferpan",
    "V S Distrib Ltda",
    "Mercante Dist Mat Elet",
    "Multinacional Dist Mat Const",
    "Inovação Atacado",
    "Ferragens Gerais",
    "Comercial Rofe",
    "Center Fertin",
    "Depedil Dist Mat",
    "Uehara Com Mat Elet Hidr",
    "Esperança Nordeste",
    "Casa Cardão",
    "Comercial Dist Bonfiglioli",
    "Coelho Gançalo e Filhos"
]
